#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Project versioning (centralized)
version=0.0.1
versionCode=1

nativePackageVersion=1.0.0

# Silence warnings coming from dependencies that we don't control
systemProp.org.gradle.deprecation.trace=true
